name:                HaskellExercises01
version:             0.1.0.0
github:              "dalvescb/HaskellExercises01"
license:             BSD3
author:              "Curtis D'Alves"
maintainer:          "curtis.dalves@gamil.com"
copyright:           "(c) Curtis D'Alves 2020"
extra-source-files:  []

description:         Please see the exercise PDF.

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- hspec

library:
  source-dirs: src

tests:
  HaskellExercises01-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellExercises01
